import type { ConsumedItem } from "@/lib/consumed";

// One-time seed data. The live source of truth is MongoDB — run `pnpm seed`
// to load these (slugs are generated from the name). Safe to edit after seeding.
// `pickRank` drives the "top picks" pyramid (1 = best). Editable in the dashboard.
export const seedItems: Omit<ConsumedItem, "slug">[] = [
  {
    name: "Berserk",
    type: "manga",
    status: "consuming",
    genres: ["Dark Fantasy", "Action"],
    creator: "Kentaro Miura",
    chapters: 374,
    revisits: 2,
    pickRank: 2,
    comment:
      "The greatest manga ever written. Reading it slowly to make it last.",
  },
  {
    name: "Chainsaw Man",
    type: "manga",
    status: "consuming",
    genres: ["Action", "Horror"],
    creator: "Tatsuki Fujimoto",
    chapters: 170,
    comment:
      "Fujimoto is doing something no one else is doing. Every chapter is unpredictable.",
  },
  {
    name: "Neon Genesis Evangelion",
    type: "anime",
    status: "completed",
    genres: ["Mecha", "Psychological"],
    studio: "Gainax",
    year: 1995,
    episodes: 26,
    rating: 10,
    revisits: 3,
    pickRank: 5,
    comment:
      "Rewatching it every few years feels like a different experience each time.",
    completedAt: "2025-04-20",
  },
  {
    name: "Parasite",
    type: "movie",
    status: "completed",
    genres: ["Thriller", "Drama"],
    creator: "Bong Joon-ho",
    year: 2019,
    rating: 10,
    revisits: 4,
    pickRank: 1,
    comment:
      "Perfect film. Gets better every watch. The basement scene never loses its punch.",
    completedAt: "2025-03-15",
  },
  {
    name: "The Sopranos",
    type: "show",
    status: "completed",
    genres: ["Drama", "Crime"],
    studio: "HBO",
    year: 1999,
    episodes: 86,
    rating: 10,
    revisits: 2,
    pickRank: 6,
    comment:
      "The best written show ever made. Tony Soprano is the most complex character in TV history.",
    completedAt: "2025-02-28",
  },
  {
    name: "Vinland Saga",
    type: "manga",
    status: "completed",
    genres: ["Historical", "Action"],
    creator: "Makoto Yukimura",
    chapters: 210,
    rating: 10,
    revisits: 1,
    pickRank: 7,
    comment:
      "The Farmland arc is one of the greatest arcs in manga history. A complete transformation.",
    completedAt: "2025-01-10",
  },
  {
    name: "2001: A Space Odyssey",
    type: "movie",
    status: "completed",
    genres: ["Sci-Fi"],
    creator: "Stanley Kubrick",
    year: 1968,
    rating: 10,
    revisits: 5,
    pickRank: 3,
    comment:
      "The film that made me care about cinema. HAL 9000 is still terrifying.",
    completedAt: "2024-12-20",
  },
  {
    name: "Arrival",
    type: "movie",
    status: "completed",
    genres: ["Sci-Fi", "Drama"],
    creator: "Denis Villeneuve",
    year: 2016,
    rating: 9,
    revisits: 2,
    comment:
      "The most emotional sci-fi film I've seen. Language as the central idea is so elegant.",
    completedAt: "2024-11-05",
  },
  {
    name: "The Wire",
    type: "show",
    status: "pending",
    genres: ["Crime", "Drama"],
    studio: "HBO",
    year: 2002,
    episodes: 60,
    comment: "Everyone says it's the best. It's next on the list.",
  },
  {
    name: "Hunter x Hunter",
    type: "anime",
    status: "completed",
    genres: ["Action", "Adventure"],
    studio: "Madhouse",
    year: 2011,
    episodes: 148,
    rating: 9,
    revisits: 1,
    pickRank: 4,
    comment:
      "Chimera Ant arc is the most ambitious storytelling I've seen in anime.",
    completedAt: "2024-10-18",
  },
  {
    name: "Goodfellas",
    type: "movie",
    status: "completed",
    genres: ["Crime", "Drama"],
    creator: "Martin Scorsese",
    year: 1990,
    rating: 10,
    revisits: 6,
    pickRank: 8,
    comment: "Could watch this forever. The editing is a masterclass.",
    completedAt: "2024-09-30",
  },
  {
    name: "Nausicaä of the Valley of the Wind",
    type: "manga",
    status: "completed",
    genres: ["Sci-Fi", "Fantasy"],
    creator: "Hayao Miyazaki",
    volumes: 7,
    rating: 10,
    revisits: 1,
    pickRank: 9,
    comment:
      "Better than the film. One of the most detailed fictional worlds ever built on paper.",
    completedAt: "2024-08-14",
  },
  {
    name: "Succession",
    type: "show",
    status: "dropped",
    genres: ["Drama", "Comedy"],
    studio: "HBO",
    year: 2018,
    episodes: 12,
    comment:
      "Watched a season. Great writing but couldn't connect with any character.",
  },
  {
    name: "Re: Zero",
    type: "anime",
    status: "consuming",
    genres: ["Fantasy", "Isekai"],
    studio: "White Fox",
    year: 2016,
    episodes: 50,
    rating: 10,
    comment:
      "Started watching it for fun, but got hooked by the complex characters and time loop mechanics.",
  },
];
